//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulingBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulingBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numbers.&lt;br&gt;e.g. 60.
        /// </summary>
        internal static string Text_AlertDuration {
            get {
                return ResourceManager.GetString("Text_AlertDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only E-mail addresses.&lt;br&gt;e.g. abc@company.com, def@government.gov.
        /// </summary>
        internal static string Text_AlertEmailAddresses {
            get {
                return ResourceManager.GetString("Text_AlertEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter.
        /// </summary>
        internal static string Text_AlertEmailAddressesNumber1 {
            get {
                return ResourceManager.GetString("Text_AlertEmailAddressesNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address(es)..
        /// </summary>
        internal static string Text_AlertEmailAddressesNumber2 {
            get {
                return ResourceManager.GetString("Text_AlertEmailAddressesNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no available time. Please enter another date..
        /// </summary>
        internal static string Text_AlertNoAvailableTime {
            get {
                return ResourceManager.GetString("Text_AlertNoAvailableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numbers.&lt;br&gt;e.g. 3.
        /// </summary>
        internal static string Text_AlertNumberOfParticipants {
            get {
                return ResourceManager.GetString("Text_AlertNumberOfParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only date.&lt;br&gt;e.g. 2015-06-20.
        /// </summary>
        internal static string Text_AlertWhen {
            get {
                return ResourceManager.GetString("Text_AlertWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The meeting is arranged. Thank you!.
        /// </summary>
        internal static string Text_Arranged {
            get {
                return ResourceManager.GetString("Text_Arranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arrangement is canceled..
        /// </summary>
        internal static string Text_Canceled {
            get {
                return ResourceManager.GetString("Text_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of the meeting is .
        /// </summary>
        internal static string Text_CheckDuration1 {
            get {
                return ResourceManager.GetString("Text_CheckDuration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  min..
        /// </summary>
        internal static string Text_CheckDuration2 {
            get {
                return ResourceManager.GetString("Text_CheckDuration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will invite .
        /// </summary>
        internal static string Text_CheckEmailAddresses {
            get {
                return ResourceManager.GetString("Text_CheckEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of participants is .
        /// </summary>
        internal static string Text_CheckNumberOfParticipants1 {
            get {
                return ResourceManager.GetString("Text_CheckNumberOfParticipants1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ..
        /// </summary>
        internal static string Text_CheckNumberOfParticipants2 {
            get {
                return ResourceManager.GetString("Text_CheckNumberOfParticipants2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;&lt;tbody&gt;&lt;tr&gt;&lt;th&gt;Subject&lt;/th&gt;&lt;td&gt;.
        /// </summary>
        internal static string Text_CheckSubject1 {
            get {
                return ResourceManager.GetString("Text_CheckSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;.
        /// </summary>
        internal static string Text_CheckSubject2 {
            get {
                return ResourceManager.GetString("Text_CheckSubject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would like to hold the meeting at .
        /// </summary>
        internal static string Text_CheckWhen1 {
            get {
                return ResourceManager.GetString("Text_CheckWhen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ..
        /// </summary>
        internal static string Text_CheckWhen2 {
            get {
                return ResourceManager.GetString("Text_CheckWhen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        internal static string Text_Confirmation1 {
            get {
                return ResourceManager.GetString("Text_Confirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string Text_Confirmation2 {
            get {
                return ResourceManager.GetString("Text_Confirmation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with attendees.
        /// </summary>
        internal static string Text_Confirmation3 {
            get {
                return ResourceManager.GetString("Text_Confirmation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was scheduled. Thank you!.
        /// </summary>
        internal static string Text_Confirmation4 {
            get {
                return ResourceManager.GetString("Text_Confirmation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to book with the above setting?.
        /// </summary>
        internal static string Text_FinalConfirmation {
            get {
                return ResourceManager.GetString("Text_FinalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        internal static string Text_Hello1 {
            get {
                return ResourceManager.GetString("Text_Hello1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  san! .
        /// </summary>
        internal static string Text_Hello2 {
            get {
                return ResourceManager.GetString("Text_Hello2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;How long is the duration&lt;/b&gt; of the meeting (min)?.
        /// </summary>
        internal static string Text_PleaseEnterDuration {
            get {
                return ResourceManager.GetString("Text_PleaseEnterDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please list &lt;b&gt;all E-mail addresses&lt;/b&gt; separated by comma. For mailing list please append &apos;dl-&apos; before the email address..
        /// </summary>
        internal static string Text_PleaseEnterEmailAddresses {
            get {
                return ResourceManager.GetString("Text_PleaseEnterEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;How many participants&lt;/b&gt; you will invite for the meeting?.
        /// </summary>
        internal static string Text_PleaseEnterNumberOfParticipants {
            get {
                return ResourceManager.GetString("Text_PleaseEnterNumberOfParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, please tell me the &lt;b&gt;subject&lt;/b&gt; of the meeting..
        /// </summary>
        internal static string Text_PleaseEnterSubject {
            get {
                return ResourceManager.GetString("Text_PleaseEnterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;When&lt;/b&gt; would you like to hold the meeting?.
        /// </summary>
        internal static string Text_PleaseEnterWhen {
            get {
                return ResourceManager.GetString("Text_PleaseEnterWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the room from the following options:.
        /// </summary>
        internal static string Text_PleaseSelectRoom {
            get {
                return ResourceManager.GetString("Text_PleaseSelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the date from the following options: .
        /// </summary>
        internal static string Text_PleaseSelectSchedule {
            get {
                return ResourceManager.GetString("Text_PleaseSelectSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, please sign in by clicking the link below. &lt;br&gt;Then, please paste back the number you received in your authentication screen..
        /// </summary>
        internal static string Text_PleaseSignIn {
            get {
                return ResourceManager.GetString("Text_PleaseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        internal static string Text_TableAttendees {
            get {
                return ResourceManager.GetString("Text_TableAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Text_TableDuration {
            get {
                return ResourceManager.GetString("Text_TableDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Invitation.
        /// </summary>
        internal static string Text_TableNumberOfInvitation {
            get {
                return ResourceManager.GetString("Text_TableNumberOfInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Text_TableSchedule {
            get {
                return ResourceManager.GetString("Text_TableSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Text_TableSubject {
            get {
                return ResourceManager.GetString("Text_TableSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! This is Schedule Bot!.
        /// </summary>
        internal static string Text_Welcome {
            get {
                return ResourceManager.GetString("Text_Welcome", resourceCulture);
            }
        }
    }
}
